[workspace]

members = [
        "adder",
        "assoc_types",
        "bla",
        "denon-control",
        "dining_philosophers",
        "embed",
        "error_handling",
        "guessing_game",
        "hello_world",
        "makros",
        "matrix",
        "romans"
]
