[package]
name = "denon-control"
version = "0.1.0"
authors = ["Lutz"]
edition = '2021'

[dependencies]
getopts = "0.2"
zeroconf = "0.15"

[dev-dependencies]
mockall = "0.13.0"
assert_cmd = "2.0.16"
predicates = "3.1.2"
